version: '3.4'
#TODO rewrite to some process
    #@see https://rtfm.co.ua/linux-php-fpm-docker-stdout-i-stderr-net-logov-prilozheniya/https://rtfm.co.ua/linux-php-fpm-docker-stdout-i-stderr-net-logov-prilozheniya/
x-logging:
  &default-logging
    driver: "json-file"
    options:
        max-file: "5"
        max-size: "20m"

services:
    mailhog:
        image: mailhog/mailhog
        container_name: evaluate_app_mailhog
        restart: unless-stopped
        ports:
          - '${MAILHOG_PORT}:1025'
        logging: *default-logging

    db:
        image: mariadb
        container_name: evaluate_app_db
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
          - "${DB_EXPOSE_PORT}:3306"
        logging: *default-logging

    nginx:
        build: ./docker/nginx/build
        image: nginx
        container_name: evaluate_app_nginx
        restart: unless-stopped
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/config:/etc/nginx/conf.d:ro
            - ./app:/app
        ports:
            - "${NGINX_EXPOSE_PORT}:80"
            - "${NGINX_MAILHOG_EXPOSE_PORT}:8025"
        logging: *default-logging

    php:
        build: ./docker/php/build
        image: php-8
        container_name: evaluate_app_php
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - ./docker/php/config/msmtprc:/etc/msmtprc:ro
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
            - ./docker/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - composer:/root/.composer/cache
            - ./app:/app
        logging: *default-logging

    rabbitmq:
        build: ./docker/rabbitmq
        restart: always
        container_name: evaluate_app_rabbitmq
        image: rabbitmq:management
        hostname: rabbitmq
        ports:
            - "${RABBIT_PORT_SERVER}:5672"
            - "${RABBIT_PORT_UI}:15672"

        volumes:
            - ./rabbitmq:/var/lib/rabbitmq:cached
        logging: *default-logging

volumes:
    composer:
