version: '3.4'
#TODO rewrite to some process
    #@see https://rtfm.co.ua/linux-php-fpm-docker-stdout-i-stderr-net-logov-prilozheniya/https://rtfm.co.ua/linux-php-fpm-docker-stdout-i-stderr-net-logov-prilozheniya/
x-logging:
  &default-logging
    driver: "json-file"
    options:
        max-file: "5"
        max-size: "20m"

services:
    mailhog:
        image: mailhog/mailhog
        container_name: evaluate_app_mailhog
        restart: unless-stopped
        ports:
          - '${MAILHOG_PORT}:1025'
        logging: *default-logging

    db:
        image: mariadb
        container_name: evaluate_app_db
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
          - "${DB_EXPOSE_PORT}:3306"
        logging: *default-logging

    nginx:
        build: ./docker/nginx/build
        image: nginx
        container_name: evaluate_app_nginx
        restart: unless-stopped
        volumes:
            - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/config:/etc/nginx/conf.d:ro
            - ./app:/srv/projects
            - ./docker/nginx/acme-challenge:/usr/share/nginx/html:ro
        ports:
            - "${NGINX_EXPOSE_PORT}:80"
            - "${NGINX_ADMINER_EXPOSE_PORT}:8080"
        logging: *default-logging

    adminer:
        image: adminer
        container_name: evaluate_app_adminer
        restart: unless-stopped

    php:
        build: ./docker/php/build
        image: php-8
        container_name: evaluate_app_php
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./docker/php/config/msmtprc:/etc/msmtprc:ro
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
            - ./docker/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - composer:/root/.composer/cache
            - ./app/:/var/www/html
        logging: *default-logging

volumes:
    composer: