monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        subscription_logger:
            type: rotating_file
            path:  "php://stderr"
            level: debug
            channels: [ 'subscription_logger' ]
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
    channels:
        - 'subscription_logger'
