doctrine:
    dbal:
#        auto_commit: true
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.5.8'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci


        url: '%env(resolve:DATABASE_URL)%'
        types:
            identifier: 'App\Model\IdType'
            user_user_email: 'App\Model\User\EmailType'
            user_user_role: 'App\Model\User\RoleType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
